deploy: &deploy
    docker:
      - image: web3f/ci-commons:v1.0.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./scripts/deploy.sh

version: 2

jobs:
  buildImage:
    docker:
      - image: web3f/ci-commons:v1.0.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/matrixbot .

  integrationTests:
    docker:
      - image: web3f/ci-commons:v1.0.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishImage:
    docker:
      - image: web3f/ci-commons:v1.0.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/matrixbot

  publishChart:
    docker:
      - image: web3f/ci-commons:v1.0.0
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

  deployW3F:
    environment:
      ENVIRONMENT: w3f
    <<: *deploy

  deployComm:
    environment:
      ENVIRONMENT: community
    <<: *deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - buildImage:
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
      - publishImage:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - buildImage
            - integrationTests
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - buildImage
            - integrationTests
      - deployW3F:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - publishChart
            - publishImage
      - deployComm:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - publishChart
            - publishImage
