{{ if ne .Values.environment "ci" }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: matrixbot
  namespace: default
spec:
  secretName: matrixbot-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
  - {{ .Values.domain }}
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - {{ .Values.domain }}
{{ end }}
