apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  configuration.yaml: |
    web:
      host: '0.0.0.0'
      port: {{ .Values.port }}
    skills:
{{ toYaml .Values.skills | indent 6 }}
    connectors:
      matrix:
        mxid: {{ .Values.botUser | quote }}
        password: {{ .Values.botPassword | quote }}
        rooms:
          "main": {{ .Values.roomId | quote }}
        homeserver: {{ .Values.homeserver }}
