apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  configuration.yaml: |
    web:
      host: '0.0.0.0'
      port: {{ .Values.port }}
    skills:
    - name: alertmanager
      path: /app/skills/skill-alertmanager
    connectors:
    - name: matrix
      mxid: "{{ .Values.botUser }}"
      password: "{{ .Values.botPassword}}"
      room: "{{ .Values.roomId }}"
      homeserver: "{{ .Values.homeserver }}"
