apiVersion: v1
kind: ConfigMap
metadata:
  name: matrixbot
data:
  configuration.yaml: |
    skills:
    - name: alertmanager
      path: /app/skills/skill-alertmanager
    connectors:
    - name: matrix
      mxid: "{{ .Values.botUser }}"
      password: "{{ .Values.botPasssword}}"
      room: "{{ .Values.roomId }}"
