apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrixbot
  labels:
    app: matrixbot
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: matrixbot
  template:
    metadata:
      labels:
        app: matrixbot
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: matrixbot
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: {{ .Values.port }}
        readinessProbe:
          httpGet:
            path: /stats
            port: {{ .Values.port }}
          initialDelaySeconds: 30
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/opsdroid
      volumes:
      - name: config
        configMap:
          name: matrixbot
