{{ if ne .Values.environment "ci" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrixbot-pv-claim
  labels:
    app: matrixbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ end }}
