environments:
  production:
  ci:
  local:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:

{{- if or (eq .Environment.Name "ci") (eq .Environment.Name "local") }} 

- name: finance-matrixbot
  chart: ../charts/matrixbot
  values:
  - ./config/csv-exporter-watcher-values.yaml.gotmpl

{{- end }}
